training:
  steps: 10_0000_0000
  use_amp: true
  amp_type: "bf16"
  base_lr: 1e-5
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  every_n_train_steps: 2000 # 5000
  val_check_interval: 2000 # 4096
  limit_val_batches: 16

dataset:
  target: hy3dshape.data.dit_asl.AlignedShapeLatentModule
  params:
    #! Base setting
    batch_size: 4
    num_workers: 8
    val_num_workers: 4

    # Data 
    # train_data_list: "/mnt/data/yangzengzhi/code/Hunyuan3D-2.1/model_list_train.json"
    # val_data_list: "/mnt/data/yangzengzhi/code/Hunyuan3D-2.1/model_list_val.json"
    #train_data_list: tools/mini_trainset/preprocessed
    #val_data_list: tools/mini_trainset/preprocessed
    train_data_list: /mnt/data/yangzengzhi/data/shoe_train_data
    val_data_list: /mnt/data/yangzengzhi/data/shoe_val_data
    

    #! Image loading
    cond_stage_key: "image" # image / text / image_text
    image_size: 518
    mean: &mean [0.5, 0.5, 0.5]
    std: &std [0.5, 0.5, 0.5]

    #! Point cloud sampling
    pc_size: &pc_size 81920 #81920
    pc_sharpedge_size: &pc_sharpedge_size 0 #0
    sharpedge_label: &sharpedge_label true
    return_normal: true

    #! Augmentation
    padding: true



model:
  # target: hy3dshape.models.diffusion
  target: hy3dshape.models.vae.vae_module.VAE
  params:
    shape_model_config:
      target: hy3dshape.models.autoencoders.ShapeVAE
      # from_pretrained: tencent/Hunyuan3D-2.1
      params:
        num_latents: &num_latents 4096
        embed_dim: 64
        num_freqs: 8
        include_pi: false
        heads: 16
        width: 1024
        num_encoder_layers: 8
        num_decoder_layers: 16
        qkv_bias: false
        qk_norm: true
        scale_factor: *z_scale_factor
        geo_decoder_mlp_expand_ratio: 4
        geo_decoder_downsample_ratio: 1
        geo_decoder_ln_post: true
        point_feats: 4
        pc_size: *pc_size
        pc_sharpedge_size: *pc_sharpedge_size